version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - pip3 install --upgrade awscli
      - pip3 install --upgrade aws-sam-cli
      - sam --version
      - dotnet tool update -g Amazon.Lambda.Tools

  pre_build:
    commands:
      - cd NOOP
      - dotnet clean
      - dotnet restore
      - cd ../PlateDetected/
      - dotnet clean
      - dotnet restore

  build:
    commands:
      - cd ..
      - sam build
  
  post_build:
    commands:
      - sam package --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file template-export.yml

cache:
  paths:
    - '/root/.nuget/packages/**/*'
artifacts:
  type: zip
  files:
    - template-export.yml
