AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Description: >-
  Creates a state machine that manages processing of Vehicle Number Plate
  images.

Conditions:
  isProd: !Equals [ !Ref EnvironmentName, "Prod" ]

Parameters:
  EnvironmentName:
    Default: Staging
    AllowedValues: 
      - Staging
      - Prod
    Description: >-
      The name of the environment - either Staging or Prod
    Type: String

  ManualImageInspectionTargetEmailSSMParam:
    Type: 'AWS::SSM::Parameter::Value<String>'  
    Description: Email address for admin assistance
  
  TollGantryAdminActionSSMParam:
    Type: 'AWS::SSM::Parameter::Value<String>'  
    Description: Activity name for admin action

  TollGantryInsufficientCreditSSMParam:
    Type: 'AWS::SSM::Parameter::Value<String>'  
    Description: Activity name for insufficient credit

  DDBTableNameSSMParam:
    Type: 'AWS::SSM::Parameter::Value<String>'  
    Description: DynamoDB table name

  APIGWEndpointSSMParam:
    Type: 'AWS::SSM::Parameter::Value<String>'  
    Description: API GW endpoint

Resources:

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action: 'logs:*'
                Effect: Allow
                Resource: 'arn:aws:logs:*:*:*'
              - Action:
                  - 'states:DescribeActivity'
                  - 'states:GetActivityTask'
                  - 'states:SendTaskSuccess'
                  - 'states:SendTaskFailure'
                  - 'states:SendTaskHeartbeat'
                Effect: Allow
                Resource: 
                  - Ref: TollGantryAdminActionSSMParam
                  - Ref: TollGantryInsufficientCreditSSMParam                       
              - Action:
                  - 'xray:PutTelemetryRecords'
                  - 'xray:PutTraceSegments'
                Effect: Allow
                Resource: '*'
              - Action:
                - SES:SendEmail
                - SES:SendRawEmail
                Effect: Allow
                Resource: !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/{{cookiecutter.your_email_address}}
              - Action:
                  - 's3:GetObject'
                Effect: Allow
                Resource:
                  !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Join 
                        - ''
                        - - !Sub {{cookiecutter.imageupload_bucket_name}}
                          - !If
                            - isProd
                            - -prod/*
                            - -staging/*
              - Action:
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                Effect: Allow
                Resource: 
                  !Join
                    - ''
                    - - 'arn:aws:dynamodb:'
                      - Ref: 'AWS::Region'
                      - ':'
                      - Ref: 'AWS::AccountId'
                      - ':table/'
                      - Ref: DDBTableNameSSMParam
            Version: '2012-10-17'
          PolicyName: AgentAccessPolicy

  ActivityPoller:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub {{cookiecutter.project_name}}-ActivityPoller-${EnvironmentName}
      Handler: ActivityPoller/index.handler
      Runtime: nodejs10.x
      Description: Polls activities in the manual intervention state and processes them
      MemorySize: 512
      Timeout: 65
      Role:
        'Fn::GetAtt':
          - LambdaExecutionRole
          - Arn
      Tracing: Active
      Environment:
        Variables:
          EnvironmentName:
            Ref: EnvironmentName
          TargetEmailAddress:
            Ref: ManualImageInspectionTargetEmailSSMParam
          APIGWEndpoint:
            Ref: APIGWEndpointSSMParam
          StepFunctionActivityManualPlateInspection:
            Ref: TollGantryAdminActionSSMParam
          StepFunctionActivityInsufficientCredit:
            Ref: TollGantryInsufficientCreditSSMParam
          DDBTableName:
            Ref: DDBTableNameSSMParam
      Policies:
        - AdministratorAccess
      Events:
        ScheduledPoll:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

